package com.payflow.common.error;
public enum ErrorCode {
    VALIDATION_FAILED,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    IDEMPOTENCY_KEY_REUSED,
    MERCHANT_NOT_ACTIVE,
    PAYMENT_NOT_REFUNDABLE,
    REFUND_AMOUNT_EXCEEDED,
    RISK_BLOCKED,
    PROVIDER_ERROR,
    PROVIDER_UNAVAILABLE,
    LEDGER_UNBALANCED,
    RATE_LIMITED,
    AI_KEY_REQUIRED,
    AI_UNAVAILABLE,
    INTERNAL_ERROR
}
