#!/bin/sh
set -eu

BROKER_PORT="${PORT:-9092}"
BROKER_HOST="${RENDER_DISCOVERY_SERVICE:-localhost}"

export KAFKA_NODE_ID="${KAFKA_NODE_ID:-1}"
export KAFKA_PROCESS_ROLES="${KAFKA_PROCESS_ROLES:-broker,controller}"
export KAFKA_CONTROLLER_QUORUM_VOTERS="${KAFKA_CONTROLLER_QUORUM_VOTERS:-1@127.0.0.1:9093}"
export KAFKA_LISTENERS="PLAINTEXT://0.0.0.0:${BROKER_PORT},CONTROLLER://0.0.0.0:9093"
export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${BROKER_HOST}:${BROKER_PORT}"
export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
export KAFKA_INTER_BROKER_LISTENER_NAME="PLAINTEXT"
export KAFKA_CONTROLLER_LISTENER_NAMES="CONTROLLER"
export KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR="1"
export KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR="1"
export KAFKA_TRANSACTION_STATE_LOG_MIN_ISR="1"
export KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS="0"
export KAFKA_AUTO_CREATE_TOPICS_ENABLE="true"
export KAFKA_LOG_DIRS="/var/lib/kafka/data"
export KAFKA_HEAP_OPTS="${KAFKA_HEAP_OPTS:--Xms256m -Xmx384m}"
export CLUSTER_ID="${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}"

exec /etc/confluent/docker/run
